"""
Problem 61
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	    P4,n=n2	 	        1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, 
is represented by a different number in the set.
"""

from itertools import permutations

def figurate_number(sides, n):
    if sides == 3:
        return n*(n+1)/2

    if sides == 4:
        return n**2

    if sides == 5:
        return n*(3*n-1)/2

    if sides == 6:
        return n*(2*n-1)

    if sides == 7:
        return n*(5*n-3)/2

    if sides == 8:
        return n*(3*n-2)


def find_numbers(x):
    for i in range(3,9):
        for j in range(1, 1000):
            num = int(figurate_number(i,j))
            if 999 < num < 10000:
                x[i].append(num)


def find_solution(x,a,b,c,d,e):
    shape_converter = {3:'Triangle', 4:'Square',5:'Pentagon',6:'Hexagon',7:'Heptagon',8:'Octagon'}
    for p in x[3]:
        for q in x[a]:
            if str(p)[2:] == str(q)[:2]:
                for r in x[b]:
                    if str(q)[2:] == str(r)[:2]:
                        for s in x[c]:
                            if str(r)[2:] == str(s)[:2]:
                                for t in x[d]:
                                    if str(s)[2:] == str(t)[:2]:
                                        for u in x[e]:
                                            if str(t)[2:] == str(u)[:2] and str(u)[2:] == str(p)[:2]:
                                                print(f'{shape_converter[3]}: {p}\n{shape_converter[a]}: {q}\n{shape_converter[b]}: {r}\n{shape_converter[c]}: {s}\n{shape_converter[d]}: {t}\n{shape_converter[e]}: {u}')
                                                print(f'\nSum: {sum([p,q,r,s,t,u])}')
                                                

def calculate():
    all_numbers = {3:[], 4:[], 5:[], 6:[], 7:[], 8:[]}
    find_numbers(all_numbers)
    perm = permutations([4,5,6,7,8],5) 
    for i in list(perm):
        find_solution(all_numbers,i[0],i[1],i[2],i[3],i[4])


if __name__ == "__main__":
    calculate()